In [3]:
import numpy as np

In [7]:
array = np.array([[1,2,3],
               [2,3,4]])
print(array)
print(array.ndim)
print(array.shape)
print(array.size)

[[1 2 3]
 [2 3 4]]
2
(2, 3)
6


In [15]:
array1 = np.array([2,3,4],dtype=np.float32)
print(array.dtype)

float32


In [16]:
a = np.array([[1,2,3],
                 [2,3,4]])

In [25]:
b =np.empty((3,4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
c =  np.arange(12).reshape(3,4)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
d = np.linspace(1,10,12).reshape(2,6)
print(d)

[[ 1.          1.81818182  2.63636364  3.45454545  4.27272727  5.09090909]
 [ 5.90909091  6.72727273  7.54545455  8.36363636  9.18181818 10.        ]]


In [50]:
a1 = np.array([[3,4],
                   [0,1]])
b1 =np.arange(4).reshape(2,2)
print(np.min(a1,axis =0))


[0 1]
